# CodeRabbit Configuration for AMSteel Survey Project
# This file configures CodeRabbit AI code review settings

# Language settings
language: "en"  # Change to "ar" for Arabic if needed

# Project-specific settings
project:
  name: "AMSteel Survey System"
  type: "fullstack"
  frontend: "React + TypeScript + Vite"
  backend: "Node.js + Express + TypeScript"
  database: "PostgreSQL"
  styling: "Tailwind CSS"
  i18n: "i18next"

# Review settings
review:
  # Enable automatic reviews for pull requests
  auto_review: true
  
  # Focus areas for this project
  focus_areas:
    - "code_quality"
    - "security"
    - "performance"
    - "accessibility"
    - "internationalization"  # Important for your multi-language project
  
  # File patterns to include/exclude
  include_patterns:
    - "src/**/*.{ts,tsx,js,jsx}"
    - "backend/src/**/*.{ts,js}"
    - "*.{json,md,yaml,yml}"
  
  exclude_patterns:
    - "node_modules/**"
    - "dist/**"
    - "build/**"
    - "*.log"
    - "package-lock.json"

# Custom instructions for this project
instructions: |
  This is a React/TypeScript survey application with:
  - Frontend: React + TypeScript + Vite + Tailwind CSS
  - Backend: Node.js + TypeScript + Express
  - Multi-language support (Arabic/English)
  - Survey functionality with different user roles (Admin, Developer, Employee, Public)
  
  Please focus on:
  1. TypeScript type safety and strict typing
  2. React best practices and hooks usage
  3. Accessibility compliance (WCAG 2.1)
  4. Internationalization (i18n) implementation
  5. Security best practices (XSS, CSRF, SQL injection)
  6. Performance optimization (React.memo, useMemo, useCallback)
  7. Code consistency and maintainability
  8. Survey-specific security (data validation, user permissions)
  9. RTL (Right-to-Left) support for Arabic
  10. Database query optimization
  11. API endpoint security and validation
  12. Error handling and logging
  13. Testing coverage and quality
  14. Code documentation and comments

# Notification settings
notifications:
  # Notify on high-priority issues
  high_priority: true
  
  # Notify on security issues
  security: true
  
  # Notify on performance issues
  performance: true

# Integration settings
integrations:
  # Enable GitHub integration
  github: true
  
  # Enable comments on pull requests
  pr_comments: true
  
  # Enable suggestions for code improvements
  suggestions: true
